import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { useEffect, useLayoutEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import { MantineProvider, Button, Container, Box, Image, Grid, ScrollArea, MediaQuery, SimpleGrid, Overlay, CloseButton } from '@mantine/core'

  /*TODO
  1. SOP or REGEX listening SRC IMAGE
  2. Delete Image
  3. Duplicate Image
  4. Input Auto Next
  5. Empty Image
    */

const DragOverListener = (e: any) => {
  e.preventDefault()
}
const Index: NextPage = () => {
  return (
    <MantineProvider
    theme={{
      fontFamily: 'Open Sans, sans serif',
      colorScheme: 'dark'
    }}
     >
      <App />
    </MantineProvider>
  )
}
const App: NextPage = () => {
  const [imageURLs, setImageURL] = useState<string[]>([])
  const DropListener = (e: any) => {
    e.stopPropagation();
    e.preventDefault(); 
    const src: string = e.dataTransfer.getData('text/html')
    if(src.split('class').length === 0) return

    let imgURL: string = ''
    imgURL = src.split('srcset')[1].split('"')[1].split(' ')[6]
    sessionStorage.setItem('state', JSON.stringify([...imageURLs, imgURL]));
    setImageURL([...imageURLs, imgURL])
  }
  const InputFocusSelect = (e: any) => {
    // focus autoselect
  }
  const FormSubmit = (e: any) => {
    e.preventDefault()
  }

  const DeleteImage = (index: number) => {
    setImageURL(imageURLs.splice(index, 1))
  }
  useEffect(() => {
    // initiliaze
    console.log('useEfffect')
    if (!imageURLs.length && sessionStorage.getItem('state')) {
      setImageURL(JSON.parse(sessionStorage.getItem('state') || ''))
    } 
  }, [imageURLs])
  return (
    <Container >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <Container padding={10}>
        Timer
        <Link href="/activity"><Button variant="outline" style={{ margin: 10 }}>1 Minutes</Button></Link>
        <Link href="/activity"><Button variant="outline" style={{ margin: 10 }}>3 Minutes</Button></Link>
        <Link href="/activity"><Button variant="outline" style={{ margin: 10 }}>5 Minutes</Button></Link>
       </Container> 
        <Box
          sx = {theme => ({
            padding: theme.spacing.md,
            borderRadius: theme.radius.md,
            marginTop: theme.spacing.md
          })}
          onDrop={DropListener}
          onDragOver={DragOverListener} 
          className={styles.drag__container}>
          <div className={styles.drag__title}>Drop Your Image Here</div>
          <ScrollArea
            style={{height: "70vh"}} >
            <SimpleGrid
              cols={4}
              breakpoints={[
                {maxWidth: "md", cols:3, spacing:'md'},
                {maxWidth: "sm", cols:2, spacing:'md'},
                {maxWidth: "xs", cols:1, spacing:'md'},
              ]}
              >
                {
                  imageURLs.map((url, index) => {
                    return (
                      <div key={index} style={{margin: "auto", height:"100%", position:'relative'}}>
                        <CloseButton 
                          onClick={() => {
                            const image: string[] = imageURLs
                            image.splice(index, 1)
                            console.log(image)
                            sessionStorage.setItem('state', JSON.stringify([...image]));
                            setImageURL([...image])
                            this
                          }}
                          color="gray"
                          style={{zIndex:3, position:'absolute', right:0, opacity:0.3}} />
                        <Image 
                          radius="md"
                          style={{margin: "auto"}}
                          width={200}
                          src={url}
                           />
                      </div>
                    )
                  })
                }
            </SimpleGrid>
          </ScrollArea>
        </Box>
    </Container>
  )
}

export default Index
